import type {
  Location,
  ComplianceRecord,
  ActivityEvent,
  Comment,
  Notification,
  User,
  ClassroomAgeGroup,
  ComplianceCategory,
  MaintenanceRequest,
  MaintenanceCategory,
  OperationsRecordType,
  SupplyRequest,
  SupplyCategory,
} from "./types"

export const COMPLIANCE_CATEGORIES: ComplianceCategory[] = [
  "Licensing",
  "Health & Safety",
  "Drills",
  "Child Files",
  "Staff Files",
  "Classroom Observations",
  "CCIR / Critical Incidents",
  "Parent Complaints",
  "Staff Complaints",
]

export const OPERATIONS_RECORD_TYPES: OperationsRecordType[] = [
  "Opening Checklist",
  "Closing Checklist",
  "Playground Checklist",
  "Cleaning Checklist",
  "Other Operations Record",
]

export const CLASSROOM_AGE_GROUPS: ClassroomAgeGroup[] = [
  "Infant",
  "Toddler",
  "Twaddler",
  "Prepper",
  "Preschool",
]

export const MAINTENANCE_CATEGORIES: MaintenanceCategory[] = [
  "Plumbing",
  "Electrical",
  "HVAC",
  "Appliance",
  "Furniture / Fixture",
  "Playground",
  "Building / Facility",
  "Safety",
  "Cleaning / Sanitation",
  "Other",
]

export const MAINTENANCE_AREAS = [
  ...CLASSROOM_AGE_GROUPS,
  "Kitchen",
  "Office",
  "Lobby",
  "Restroom",
  "Playground",
  "Exterior",
  "Hallway",
  "Storage",
  "Whole Location",
  "Other",
] as const

/** Temporary configurable presets until a persisted vendor directory is introduced. */
export const MAINTENANCE_VENDOR_PRESETS = [
  { name: "In-House Maintenance", contact: "(407) 555-0100" },
  { name: "Sunshine Facility Services", contact: "(407) 555-0142" },
  { name: "Central Florida Plumbing", contact: "(407) 555-0164" },
  { name: "BrightLine Electrical", contact: "(407) 555-0187" },
] as const

export const SUPPLY_CATEGORIES: SupplyCategory[] = ["Supplies", "Furniture", "Fixtures", "Equipment", "Other"]

export const SUPPLY_AREAS = [
  ...CLASSROOM_AGE_GROUPS,
  "Kitchen",
  "Office",
  "Lobby",
  "Playground",
  "Restroom",
  "Storage",
  "Whole Location",
  "Other",
] as const

export const USERS: User[] = [
  { id: "u1", name: "Sandra Mitchell", role: "owner", initials: "SM" },
  { id: "u2", name: "Rachel Torres", role: "director", locationId: "loc1", initials: "RT" },
  { id: "u3", name: "James Okafor", role: "director", locationId: "loc2", initials: "JO" },
  { id: "u4", name: "Priya Nair", role: "director", locationId: "loc3", initials: "PN" },
  { id: "u5", name: "Morgan Ellis", role: "assistant_director", locationId: "loc2", initials: "ME" },
]

export const LOCATIONS: Location[] = [
  {
    id: "loc1",
    name: "Lake Mary Learning Center",
    director: "Rachel Torres",
    directorId: "u2",
    address: "1420 Crystal Lake Rd, Lake Mary, FL 32746",
    phone: "(407) 555-0182",
    capacity: 72,
  },
  {
    id: "loc2",
    name: "Winter Park Learning Center",
    director: "James Okafor",
    directorId: "u3",
    address: "310 Fairbanks Ave, Winter Park, FL 32789",
    phone: "(407) 555-0241",
    capacity: 88,
  },
  {
    id: "loc3",
    name: "Sanford Learning Center",
    director: "Priya Nair",
    directorId: "u4",
    address: "2850 Orlando Dr, Sanford, FL 32773",
    phone: "(407) 555-0317",
    capacity: 64,
  },
]

export const RECORDS: ComplianceRecord[] = [
  {
    id: "rec16",
    title: "Opening Checklist — August 2025",
    locationId: "loc1",
    category: "Operations",
    workspace: "operations",
    recordType: "Opening Checklist",
    status: "New",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-08-08",
    lastUpdated: "2025-08-08",
    description: "Recurring opening checklist covering facility walk-through, classroom readiness, playground inspection, and required opening documentation.",
    fileNames: ["Opening_Checklist_August_2025.pdf"],
    tags: ["opening checklist", "monthly", "operations"],
    reportingPeriod: { cadence: "MONTHLY", month: "08", year: "2025" },
  },
  {
    id: "rec17",
    title: "Closing Checklist — August 2025",
    locationId: "loc2",
    category: "Operations",
    workspace: "operations",
    recordType: "Closing Checklist",
    status: "Reviewed",
    uploadedBy: "Morgan Ellis",
    uploadedById: "u5",
    uploadDate: "2025-08-08",
    lastUpdated: "2025-08-08",
    description: "End-of-day operational checklist covering classroom closeout, alarm procedures, medication storage, and final facility walk-through.",
    fileNames: ["Closing_Checklist_August_2025.pdf"],
    tags: ["closing checklist", "monthly", "operations"],
    reportingPeriod: { cadence: "MONTHLY", month: "08", year: "2025" },
  },
  {
    id: "rec18",
    title: "Playground Checklist — August 2025",
    locationId: "loc3",
    category: "Operations",
    workspace: "operations",
    recordType: "Playground Checklist",
    classroomAgeGroup: "Preschool",
    area: "North Playground",
    status: "Needs Attention",
    uploadedBy: "Priya Nair",
    uploadedById: "u4",
    uploadDate: "2025-08-07",
    lastUpdated: "2025-08-08",
    description: "Monthly playground readiness checklist. Follow-up requested for the north gate latch before the next outdoor period.",
    fileNames: ["Playground_Checklist_August_2025.pdf", "North_Gate_Latch.jpg"],
    tags: ["playground", "monthly", "operations"],
    reportingPeriod: { cadence: "MONTHLY", month: "08", year: "2025" },
  },
  {
    id: "rec20",
    title: "Cleaning Checklist — Week of August 11, 2025",
    locationId: "loc2",
    category: "Operations",
    workspace: "operations",
    recordType: "Cleaning Checklist",
    area: "Kitchen",
    status: "Reviewed",
    uploadedBy: "James Okafor",
    uploadedById: "u3",
    uploadDate: "2025-08-11",
    lastUpdated: "2025-08-12",
    description: "Weekly deep-cleaning checklist covering kitchen, restrooms, and shared classroom surfaces.",
    fileNames: ["Cleaning_Checklist_Week_Aug11_2025.pdf"],
    tags: ["cleaning checklist", "weekly", "operations"],
    reportingPeriod: { cadence: "WEEKLY", weekOf: "2025-08-11" },
  },
  {
    id: "rec21",
    title: "Health & Safety Inspection — August 2025",
    locationId: "loc1",
    category: "Health & Safety",
    status: "New",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-08-09",
    lastUpdated: "2025-08-09",
    description: "Monthly internal health and safety walk-through covering supervision, sanitation, and hazard checks outside of scheduled drills.",
    fileNames: ["Health_Safety_Inspection_August_2025.pdf"],
    tags: ["health & safety", "monthly"],
    reportingPeriod: { cadence: "MONTHLY", month: "08", year: "2025" },
  },
  {
    id: "rec19",
    title: "Operations — Kitchen Inventory Review",
    locationId: "loc1",
    category: "Operations",
    workspace: "operations",
    recordType: "Other Operations Record",
    area: "Kitchen",
    status: "Archived",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-07-18",
    lastUpdated: "2025-08-01",
    description: "One-time operational review of kitchen inventory labeling, storage rotation, and receiving documentation.",
    fileNames: ["Kitchen_Inventory_Review.pdf"],
    tags: ["kitchen", "inventory", "operations"],
  },
  {
    id: "rec15",
    title: "Infant Classroom Observation — August",
    locationId: "loc1",
    category: "Classroom Observations",
    classroomAgeGroup: "Infant",
    observationMonth: "2025-08",
    status: "Reviewed",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-08-06",
    lastUpdated: "2025-08-07",
    description: "Monthly classroom observation focused on arrival routines, safe sleep documentation, and responsive caregiving. Notes reviewed with the lead teacher.",
    fileNames: ["Infant_Observation_August_2025.pdf", "Infant_Room_August.jpg"],
    tags: ["monthly observation", "infant", "August"],
    reportingPeriod: { cadence: "MONTHLY", month: "08", year: "2025" },
  },
  {
    id: "rec14",
    title: "Toddler Classroom Observation — August",
    locationId: "loc2",
    category: "Classroom Observations",
    classroomAgeGroup: "Toddler",
    observationMonth: "2025-08",
    status: "Needs Attention",
    uploadedBy: "Morgan Ellis",
    uploadedById: "u5",
    uploadDate: "2025-08-05",
    lastUpdated: "2025-08-06",
    description: "Monthly observation of transitions, supervision, and learning-center setup. Follow-up requested for transition coverage notes.",
    fileNames: ["Toddler_Observation_August_2025.pdf"],
    tags: ["monthly observation", "toddler", "follow-up"],
    reportingPeriod: { cadence: "MONTHLY", month: "08", year: "2025" },
  },
  {
    id: "rec13",
    title: "Preschool Classroom Observation — August",
    locationId: "loc3",
    category: "Classroom Observations",
    classroomAgeGroup: "Preschool",
    observationMonth: "2025-08",
    status: "New",
    uploadedBy: "Priya Nair",
    uploadedById: "u4",
    uploadDate: "2025-08-05",
    lastUpdated: "2025-08-05",
    description: "Monthly observation covering classroom organization, active supervision, and lesson-plan alignment.",
    fileNames: ["Preschool_Observation_August_2025.pdf", "Preschool_Centers_August.jpg"],
    tags: ["monthly observation", "preschool", "August"],
    reportingPeriod: { cadence: "MONTHLY", month: "08", year: "2025" },
  },
  {
    id: "rec1",
    title: "Annual DCF Licensing Renewal – 2025",
    locationId: "loc1",
    category: "Licensing",
    status: "Needs Attention",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-07-28",
    lastUpdated: "2025-07-30",
    description:
      "Annual license renewal application submitted to DCF. Awaiting signed director attestation page before final submission.",
    fileNames: ["DCF_License_Renewal_2025_Draft.pdf"],
    tags: ["DCF", "annual", "renewal"],
    relatedRef: "Staff: Rachel Torres",
  },
  {
    id: "rec2",
    title: "Fire Drill – July 2025",
    locationId: "loc1",
    // Migrated from the retired "Health & Safety Drills" category; this is a drill record.
    category: "Drills",
    status: "New",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-07-22",
    lastUpdated: "2025-07-22",
    description:
      "Monthly fire drill conducted at 10:15 AM. All 68 children and 9 staff evacuated within 2 minutes 38 seconds. No issues noted.",
    fileNames: ["Fire_Drill_July2025_LM.pdf", "Fire_Drill_July2025_photo.jpg"],
    tags: ["fire drill", "monthly", "evacuation"],
    reportingPeriod: { cadence: "MONTHLY", month: "07", year: "2025" },
  },
  {
    id: "rec3",
    title: "Child Enrollment File – Aiden Clark",
    locationId: "loc1",
    category: "Child Files",
    status: "Reviewed",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-07-10",
    lastUpdated: "2025-07-15",
    description:
      "Complete enrollment packet for Aiden Clark (DOB 03/14/2021). Includes immunization records, emergency contacts, and signed parent handbook acknowledgment.",
    fileNames: ["Clark_Aiden_Enrollment_2025.pdf"],
    tags: ["enrollment", "new child"],
    relatedRef: "Child: Aiden Clark",
  },
  {
    id: "rec4",
    title: "Staff Background Check – Maria Gonzalez",
    locationId: "loc2",
    category: "Staff Files",
    status: "Reviewed",
    uploadedBy: "James Okafor",
    uploadedById: "u3",
    uploadDate: "2025-07-05",
    lastUpdated: "2025-07-08",
    description:
      "Level 2 background screening results for Maria Gonzalez. Clear results received. File updated in DCF portal.",
    fileNames: ["Gonzalez_Maria_L2_Clearance.pdf"],
    tags: ["background check", "Level 2", "new hire"],
    relatedRef: "Staff: Maria Gonzalez",
  },
  {
    id: "rec5",
    title: "Parent Complaint – Incident Report #2025-019",
    locationId: "loc2",
    category: "Parent Complaints",
    status: "Needs Attention",
    uploadedBy: "James Okafor",
    uploadedById: "u3",
    uploadDate: "2025-07-25",
    lastUpdated: "2025-07-27",
    description:
      "Parent complaint received regarding playground supervision on 7/24. Full written statement and director response attached. Follow-up meeting scheduled.",
    fileNames: ["ParentComplaint_2025-019.pdf", "DirectorResponse_2025-019.pdf"],
    tags: ["complaint", "playground", "supervision"],
  },
  {
    id: "rec6",
    title: "CCIR – Allergic Reaction Incident",
    locationId: "loc3",
    category: "CCIR / Critical Incidents",
    status: "Needs Attention",
    uploadedBy: "Priya Nair",
    uploadedById: "u4",
    uploadDate: "2025-07-29",
    lastUpdated: "2025-07-29",
    description:
      "Child experienced mild allergic reaction during snack time. Epi-pen administered by nurse. Parent notified. DCF reportable incident form submitted within 1-hour window.",
    fileNames: ["CCIR_AllergyIncident_072925.pdf", "EpipenAdmin_Log.pdf"],
    tags: ["CCIR", "medical", "reportable", "urgent"],
  },
  {
    id: "rec7",
    title: "Lockdown Drill – June 2025",
    locationId: "loc2",
    // Migrated from the retired "Health & Safety Drills" category; this is a drill record.
    category: "Drills",
    status: "Reviewed",
    uploadedBy: "James Okafor",
    uploadedById: "u3",
    uploadDate: "2025-06-18",
    lastUpdated: "2025-06-20",
    description:
      "Quarterly lockdown drill completed in coordination with Seminole County Sheriff. All rooms secured within 90 seconds.",
    fileNames: ["Lockdown_Drill_June2025_WP.pdf"],
    tags: ["lockdown", "quarterly", "security"],
    reportingPeriod: { cadence: "MONTHLY", month: "06", year: "2025" },
  },
  {
    id: "rec8",
    title: "State Licensing Inspection – 2025",
    locationId: "loc3",
    category: "Licensing",
    status: "New",
    uploadedBy: "Priya Nair",
    uploadedById: "u4",
    uploadDate: "2025-07-31",
    lastUpdated: "2025-07-31",
    description:
      "Unannounced state licensing inspection completed on 7/31. Inspector: Jennifer Walsh. No citations issued. Inspection report attached.",
    fileNames: ["StateInspection_2025_Sanford.pdf"],
    tags: ["inspection", "state", "DCF"],
  },
  {
    id: "rec9",
    title: "Staff Complaint – Workplace Conduct",
    locationId: "loc1",
    category: "Staff Complaints",
    status: "New",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-08-01",
    lastUpdated: "2025-08-01",
    description:
      "Written complaint filed by classroom aide regarding conduct of lead teacher. HR investigation initiated. All parties notified.",
    fileNames: ["StaffComplaint_HR_080125.pdf"],
    tags: ["HR", "conduct", "investigation"],
  },
  {
    id: "rec10",
    title: "Child Enrollment File – Sofia Rivera",
    locationId: "loc3",
    category: "Child Files",
    status: "New",
    uploadedBy: "Priya Nair",
    uploadedById: "u4",
    uploadDate: "2025-08-04",
    lastUpdated: "2025-08-04",
    description:
      "New enrollment packet for Sofia Rivera (DOB 11/02/2020). Immunization records pending. Enrollment contingent on receipt within 30 days.",
    fileNames: ["Rivera_Sofia_Enrollment_2025.pdf"],
    tags: ["enrollment", "pending immunization"],
    relatedRef: "Child: Sofia Rivera",
  },
  {
    id: "rec11",
    title: "CPR / First Aid Certification – Staff Renewal",
    locationId: "loc2",
    category: "Staff Files",
    status: "Reviewed",
    uploadedBy: "James Okafor",
    uploadedById: "u3",
    uploadDate: "2025-06-30",
    lastUpdated: "2025-07-02",
    description:
      "Renewed CPR and First Aid certifications for 6 staff members. Certificates valid through June 2027. All records updated in staff files.",
    fileNames: ["CPR_Certifications_June2025_WP.pdf"],
    tags: ["CPR", "certification", "renewal"],
  },
  {
    id: "rec12",
    title: "Tornado Drill – May 2025",
    locationId: "loc1",
    // Migrated from the retired "Health & Safety Drills" category; this is a drill record.
    category: "Drills",
    status: "Archived",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-05-14",
    lastUpdated: "2025-06-01",
    description:
      "Annual tornado drill completed. All children moved to interior hallways within 85 seconds. Archived after review cycle.",
    fileNames: ["Tornado_Drill_May2025_LM.pdf"],
    tags: ["tornado", "annual", "weather"],
    reportingPeriod: { cadence: "MONTHLY", month: "05", year: "2025" },
  },
]

export const MAINTENANCE_REQUESTS: MaintenanceRequest[] = [
  {
    id: "maint1",
    title: "North Toilet — Toddler Restroom",
    description: "The north toilet intermittently runs and leaks around the supply connection. This is the third service visit for the same fixture this year.",
    locationId: "loc1",
    classroomAgeGroup: "Toddler",
    area: "Restroom",
    category: "Plumbing",
    priority: "Medium",
    submittedBy: "Rachel Torres",
    submittedById: "u2",
    createdAt: "2025-08-02T09:20:00",
    lastUpdated: "2025-08-06T15:40:00",
    approvalStatus: "Approved",
    maintenanceStatus: "Completed",
    assignedTo: "Sunshine Facility Services",
    vendor: "Sunshine Facility Services",
    vendorContact: "dispatch@sunshinefacility.example",
    scheduledDate: "2025-08-05",
    estimatedCost: 225,
    finalCost: 245,
    completedAt: "2025-08-06T15:40:00",
    originalPhotos: [{ name: "north-toilet-leak.jpg", uploadedAt: "2025-08-02T09:20:00", uploadedBy: "Rachel Torres" }],
    completionPhotos: [{ name: "north-toilet-repaired.jpg", uploadedAt: "2025-08-06T15:35:00", uploadedBy: "Rachel Torres" }],
    invoices: [{ name: "sunshine-invoice-1842.pdf", uploadedAt: "2025-08-06T15:38:00", uploadedBy: "Rachel Torres" }],
    assetName: "North Toilet",
    assetType: "Commercial toilet",
    repeatIssueKey: "loc1-toddler-restroom-north-toilet",
    repeatRepairCount: 3,
    repeatRecordedCost: 740,
    repeatRepairPeriodMonths: 12,
    archived: false,
  },
  {
    id: "maint2",
    title: "Preschool Classroom AC Not Cooling",
    description: "The classroom remained above 78°F after the thermostat was lowered. Airflow is present but not cool.",
    locationId: "loc2",
    classroomAgeGroup: "Preschool",
    area: "Preschool",
    category: "HVAC",
    priority: "High",
    submittedBy: "Morgan Ellis",
    submittedById: "u5",
    createdAt: "2025-08-08T10:15:00",
    lastUpdated: "2025-08-08T10:15:00",
    approvalStatus: "Awaiting Approval",
    maintenanceStatus: "Submitted",
    estimatedCost: 850,
    originalPhotos: [{ name: "preschool-thermostat.jpg", uploadedAt: "2025-08-08T10:15:00", uploadedBy: "Morgan Ellis" }],
    completionPhotos: [],
    invoices: [],
    assetName: "Preschool HVAC Unit",
    assetType: "HVAC",
    repeatIssueKey: "loc2-preschool-hvac",
    archived: false,
  },
  {
    id: "maint3",
    title: "Playground Gate Latch Broken",
    description: "The north playground gate no longer latches without lifting the gate. Area is secured pending repair.",
    locationId: "loc3",
    area: "Playground",
    category: "Playground",
    priority: "High",
    submittedBy: "Priya Nair",
    submittedById: "u4",
    createdAt: "2025-08-07T08:05:00",
    lastUpdated: "2025-08-09T09:30:00",
    approvalStatus: "Approved",
    maintenanceStatus: "In Progress",
    assignedTo: "In-House Maintenance",
    vendor: "In-House Maintenance",
    scheduledDate: "2025-08-09",
    estimatedCost: 120,
    originalPhotos: [{ name: "north-gate-latch.jpg", uploadedAt: "2025-08-07T08:05:00", uploadedBy: "Priya Nair" }],
    completionPhotos: [],
    invoices: [],
    assetName: "North Playground Gate",
    assetType: "Gate latch",
    archived: false,
  },
  {
    id: "maint4",
    title: "Infant Classroom Cabinet Hinge",
    description: "Lower cabinet hinge pulled away from the cabinet frame. Cabinet was emptied until the hinge could be replaced.",
    locationId: "loc1",
    classroomAgeGroup: "Infant",
    area: "Infant",
    category: "Furniture / Fixture",
    priority: "Low",
    submittedBy: "Rachel Torres",
    submittedById: "u2",
    createdAt: "2025-08-01T12:10:00",
    lastUpdated: "2025-08-03T11:20:00",
    approvalStatus: "Not Required",
    maintenanceStatus: "Completed",
    assignedTo: "In-House Maintenance",
    vendor: "In-House Maintenance",
    finalCost: 65,
    completedAt: "2025-08-03T11:20:00",
    originalPhotos: [{ name: "infant-cabinet-hinge.jpg", uploadedAt: "2025-08-01T12:10:00", uploadedBy: "Rachel Torres" }],
    completionPhotos: [{ name: "infant-cabinet-complete.jpg", uploadedAt: "2025-08-03T11:20:00", uploadedBy: "Rachel Torres" }],
    invoices: [],
    assetName: "Infant Storage Cabinet",
    assetType: "Cabinet hardware",
    archived: false,
  },
  {
    id: "maint5",
    title: "Kitchen Sink Leak",
    description: "Slow leak beneath the prep sink appears when the faucet is running. A catch pan is in place while a replacement part is sourced.",
    locationId: "loc2",
    area: "Kitchen",
    category: "Plumbing",
    priority: "Medium",
    submittedBy: "James Okafor",
    submittedById: "u3",
    createdAt: "2025-08-05T14:25:00",
    lastUpdated: "2025-08-08T16:00:00",
    approvalStatus: "Approved",
    maintenanceStatus: "Waiting",
    approvalNote: "Approved; proceed when replacement valve arrives.",
    assignedTo: "Central Florida Plumbing",
    vendor: "Central Florida Plumbing",
    vendorContact: "(407) 555-0164",
    scheduledDate: "2025-08-12",
    estimatedCost: 310,
    originalPhotos: [{ name: "kitchen-sink-leak.jpg", uploadedAt: "2025-08-05T14:25:00", uploadedBy: "James Okafor" }],
    completionPhotos: [],
    invoices: [],
    assetName: "Kitchen Prep Sink",
    assetType: "Sink fixture",
    archived: false,
  },
  {
    id: "maint6",
    title: "Lobby Ceiling Tile Replacement",
    description: "Replaced a stained ceiling tile after the roof inspection confirmed no active leak.",
    locationId: "loc3",
    area: "Lobby",
    category: "Building / Facility",
    priority: "Low",
    submittedBy: "Priya Nair",
    submittedById: "u4",
    createdAt: "2025-07-10T10:00:00",
    lastUpdated: "2025-07-18T13:45:00",
    approvalStatus: "Not Required",
    maintenanceStatus: "Completed",
    assignedTo: "In-House Maintenance",
    vendor: "In-House Maintenance",
    finalCost: 38,
    completedAt: "2025-07-12T09:30:00",
    originalPhotos: [],
    completionPhotos: [{ name: "lobby-ceiling-complete.jpg", uploadedAt: "2025-07-12T09:30:00", uploadedBy: "Priya Nair" }],
    invoices: [],
    assetName: "Lobby Ceiling Tile",
    assetType: "Ceiling finish",
    archived: true,
  },
]

export const FUTURE_MAINTENANCE_INSIGHT = MAINTENANCE_REQUESTS[0]

export const SUPPLY_REQUESTS: SupplyRequest[] = [
  {
    id: "supply1", locationId: "loc1", area: "Preschool", classroomAgeGroup: "Preschool",
    category: "Furniture", title: "Preschool Classroom Rug Replacement", itemName: "Preschool Classroom Rug Replacement",
    description: "The current rug is torn along one edge and can no longer be secured safely. Photo attached for owner review.",
    quantity: 1, unitCost: 425, estimatedTotal: 425, vendor: "Lakeshore Learning", requestedAt: "2025-08-09T09:15:00",
    neededBy: "2025-08-20", priority: "High", approvalRequired: true, approvalStatus: "Awaiting Approval",
    fulfillmentStatus: "Submitted", submittedBy: "Rachel Torres", requestedBy: "Rachel Torres", submittedById: "u2", requestedById: "u2", lastUpdated: "2025-08-09T09:15:00",
    photos: [{ name: "preschool-rug-damage.jpg", uploadedAt: "2025-08-09T09:15:00", uploadedBy: "Rachel Torres" }], archived: false,
  },
  {
    id: "supply2", locationId: "loc1", area: "Infant", classroomAgeGroup: "Infant",
    category: "Supplies", title: "Infant Classroom Diapers — Monthly Supply", itemName: "Infant Classroom Diapers — Monthly Supply",
    description: "Monthly replenishment of classroom diaper supply.", quantity: 6, quantityUnit: "cases", unitCost: 51.67,
    estimatedTotal: 310, vendor: "Costco Business", requestedAt: "2025-08-07T11:30:00", priority: "Medium",
    approvalRequired: false, approvalStatus: "Not Required", fulfillmentStatus: "Approved / Ready",
    submittedBy: "Rachel Torres", requestedBy: "Rachel Torres", submittedById: "u2", requestedById: "u2", lastUpdated: "2025-08-08T08:40:00", photos: [], archived: false,
  },
  {
    id: "supply3", locationId: "loc3", area: "Playground", category: "Equipment", title: "Playground Shade Canopy Replacement", itemName: "Playground Shade Canopy Replacement",
    description: "Replacement canopy for the west play zone after wind damage.", quantity: 1, unitCost: 1850, estimatedTotal: 1850,
    vendor: "Playground Outfitters", productLink: "https://example.com/shade-canopy", requestedAt: "2025-08-01T10:00:00",
    priority: "High", approvalRequired: true, approvalStatus: "Approved", fulfillmentStatus: "Ordered",
    submittedBy: "Priya Nair", requestedBy: "Priya Nair", submittedById: "u4", requestedById: "u4", orderedAt: "2025-08-06T14:10:00", lastUpdated: "2025-08-06T14:10:00",
    photos: [{ name: "damaged-shade-canopy.jpg", uploadedAt: "2025-08-01T10:00:00", uploadedBy: "Priya Nair" }], archived: false,
  },
  {
    id: "supply4", locationId: "loc2", area: "Office", category: "Supplies", title: "Office Printer Toner", itemName: "Office Printer Toner",
    description: "Black toner cartridges for the main office printer.", quantity: 4, unitCost: 65, estimatedTotal: 260,
    finalTotal: 252, vendor: "Staples", requestedAt: "2025-07-28T08:30:00", priority: "Medium", approvalRequired: true,
    approvalStatus: "Approved", fulfillmentStatus: "Received", submittedBy: "James Okafor", requestedBy: "James Okafor", submittedById: "u3", requestedById: "u3",
    orderedAt: "2025-07-30T13:00:00", receivedAt: "2025-08-04T10:20:00", lastUpdated: "2025-08-04T10:20:00", photos: [], archived: false,
  },
  {
    id: "supply5", locationId: "loc2", area: "Toddler", classroomAgeGroup: "Toddler", category: "Furniture",
    title: "Toddler Classroom Chairs", itemName: "Toddler Classroom Chairs", description: "Eight replacement chairs for cracked and unstable classroom seating.",
    quantity: 8, unitCost: 85, estimatedTotal: 680, vendor: "Community Playthings", requestedAt: "2025-08-08T15:45:00",
    priority: "High", approvalRequired: true, approvalStatus: "Awaiting Approval", fulfillmentStatus: "Submitted",
    submittedBy: "Morgan Ellis", requestedBy: "Morgan Ellis", submittedById: "u5", requestedById: "u5", lastUpdated: "2025-08-08T15:45:00",
    photos: [{ name: "toddler-chair-damage.jpg", uploadedAt: "2025-08-08T15:45:00", uploadedBy: "Morgan Ellis" }], archived: false,
  },
  {
    id: "supply6", locationId: "loc1", area: "Storage", category: "Supplies", title: "Disposable Gloves Restock", itemName: "Disposable Gloves Restock",
    description: "Received monthly glove restock; retained for spend history.", quantity: 10, quantityUnit: "boxes", unitCost: 14,
    estimatedTotal: 140, finalTotal: 140, vendor: "HD Supply", requestedAt: "2025-07-20T09:00:00", priority: "Medium",
    approvalRequired: false, approvalStatus: "Not Required", fulfillmentStatus: "Received", submittedBy: "Rachel Torres", requestedBy: "Rachel Torres", submittedById: "u2", requestedById: "u2",
    orderedAt: "2025-07-21T09:00:00", receivedAt: "2025-07-24T12:00:00", lastUpdated: "2025-07-30T12:00:00", photos: [], archived: true,
  },
]

// Prototype-only reporting hooks; no analytics UI is included in this sprint.
export const FUTURE_SUPPLY_ANALYTICS_FIELDS = ["locationId", "area", "category", "quantity", "unitCost", "estimatedTotal", "finalTotal", "vendor", "requestedAt", "orderedAt", "receivedAt"] as const

export const ACTIVITY: ActivityEvent[] = [
  { id: "sact8", recordId: "supply4", type: "status_changed", user: "James Okafor", userId: "u3", role: "director", timestamp: "2025-08-04T10:20:00", detail: "Item received: Office Printer Toner." },
  { id: "sact7", recordId: "supply3", type: "status_changed", user: "Sandra Mitchell", userId: "u1", role: "owner", timestamp: "2025-08-06T14:10:00", detail: "Item ordered: Playground Shade Canopy Replacement." },
  { id: "sact6", recordId: "supply3", type: "status_changed", user: "Sandra Mitchell", userId: "u1", role: "owner", timestamp: "2025-08-03T09:00:00", detail: "Owner approved supply request." },
  { id: "sact5", recordId: "supply5", type: "file_uploaded", user: "Morgan Ellis", userId: "u5", role: "assistant_director", timestamp: "2025-08-08T15:46:00", detail: "Photo attached: toddler-chair-damage.jpg." },
  { id: "sact4", recordId: "supply5", type: "created", user: "Morgan Ellis", userId: "u5", role: "assistant_director", timestamp: "2025-08-08T15:45:00", detail: "Supply request submitted for Owner approval." },
  { id: "sact3", recordId: "supply2", type: "status_changed", user: "Rachel Torres", userId: "u2", role: "director", timestamp: "2025-08-08T08:40:00", detail: "Request marked Ready to Order." },
  { id: "sact2", recordId: "supply1", type: "file_uploaded", user: "Rachel Torres", userId: "u2", role: "director", timestamp: "2025-08-09T09:16:00", detail: "Photo attached: preschool-rug-damage.jpg." },
  { id: "sact1", recordId: "supply1", type: "created", user: "Rachel Torres", userId: "u2", role: "director", timestamp: "2025-08-09T09:15:00", detail: "Supply request submitted for Owner approval." },
  {
    id: "mact6",
    recordId: "maint1",
    type: "file_uploaded",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-08-06T15:38:00",
    detail: "Invoice uploaded for North Toilet — Toddler Restroom.",
  },
  {
    id: "mact5",
    recordId: "maint1",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-08-06T15:40:00",
    detail: "Repair marked Completed.",
  },
  {
    id: "mact4",
    recordId: "maint3",
    type: "status_changed",
    user: "Priya Nair",
    userId: "u4",
    role: "director",
    timestamp: "2025-08-09T09:30:00",
    detail: "Playground gate repair changed to In Progress.",
  },
  {
    id: "mact3",
    recordId: "maint5",
    type: "edited",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-08-08T16:00:00",
    detail: "Central Florida Plumbing assigned; repair is waiting for a replacement valve.",
  },
  {
    id: "mact2",
    recordId: "maint2",
    type: "created",
    user: "Morgan Ellis",
    userId: "u5",
    role: "assistant_director",
    timestamp: "2025-08-08T10:15:00",
    detail: "Maintenance request submitted and sent for Owner approval.",
  },
  {
    id: "mact1",
    recordId: "maint3",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-08-07T10:15:00",
    detail: "Owner approved the playground gate maintenance request.",
  },
  {
    id: "act19",
    recordId: "rec19",
    type: "archived",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-08-01T15:05:00",
    detail: "Kitchen inventory review archived after the operational follow-up was completed.",
  },
  {
    id: "act18",
    recordId: "rec18",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-08-08T09:20:00",
    detail: "Playground checklist marked Needs Attention.",
  },
  {
    id: "act17",
    recordId: "rec17",
    type: "created",
    user: "Morgan Ellis",
    userId: "u5",
    role: "assistant_director",
    timestamp: "2025-08-08T17:40:00",
    detail: "Closing checklist uploaded for August.",
  },
  {
    id: "act16",
    recordId: "rec16",
    type: "created",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-08-08T08:10:00",
    detail: "Opening checklist uploaded for August.",
  },
  {
    id: "act15",
    recordId: "rec15",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-08-07T14:10:00",
    detail: "Infant classroom observation marked Reviewed.",
  },
  {
    id: "act14",
    recordId: "rec14",
    type: "comment_added",
    user: "Morgan Ellis",
    userId: "u5",
    role: "assistant_director",
    timestamp: "2025-08-06T11:30:00",
    detail: "Follow-up note added to the Toddler classroom observation.",
  },
  {
    id: "act13",
    recordId: "rec13",
    type: "created",
    user: "Priya Nair",
    userId: "u4",
    role: "director",
    timestamp: "2025-08-05T16:20:00",
    detail: "Preschool monthly classroom observation uploaded.",
  },
  {
    id: "act1",
    recordId: "rec1",
    type: "created",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-07-28T09:14:00",
    detail: "Record created and document uploaded.",
  },
  {
    id: "act2",
    recordId: "rec1",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-07-30T14:22:00",
    detail: "Status changed from New to Needs Attention.",
  },
  {
    id: "act3",
    recordId: "rec2",
    type: "created",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-07-22T11:05:00",
    detail: "Record created. Drill log and photo uploaded.",
  },
  {
    id: "act4",
    recordId: "rec3",
    type: "created",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-07-10T08:30:00",
    detail: "Enrollment file created.",
  },
  {
    id: "act5",
    recordId: "rec3",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-07-15T10:11:00",
    detail: "Status changed to Reviewed.",
  },
  {
    id: "act6",
    recordId: "rec5",
    type: "created",
    user: "James Okafor",
    userId: "u3",
    role: "director",
    timestamp: "2025-07-25T15:40:00",
    detail: "Complaint report uploaded.",
  },
  {
    id: "act7",
    recordId: "rec5",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-07-27T09:05:00",
    detail: "Status changed to Needs Attention.",
  },
  {
    id: "act8",
    recordId: "rec6",
    type: "created",
    user: "Priya Nair",
    userId: "u4",
    role: "director",
    timestamp: "2025-07-29T13:58:00",
    detail: "CCIR record created. Two documents uploaded.",
  },
  {
    id: "act9",
    recordId: "rec8",
    type: "created",
    user: "Priya Nair",
    userId: "u4",
    role: "director",
    timestamp: "2025-07-31T16:30:00",
    detail: "Inspection report uploaded.",
  },
  {
    id: "act10",
    recordId: "rec9",
    type: "created",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-08-01T08:45:00",
    detail: "Staff complaint record created.",
  },
  {
    id: "act11",
    recordId: "rec10",
    type: "created",
    user: "Priya Nair",
    userId: "u4",
    role: "director",
    timestamp: "2025-08-04T10:20:00",
    detail: "New enrollment file created. Immunization records pending.",
  },
  {
    id: "act12",
    recordId: "rec12",
    type: "archived",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-06-01T11:00:00",
    detail: "Record archived after review cycle.",
  },
]

export const COMMENTS: Comment[] = [
  {
    id: "mcmt1",
    recordId: "maint5",
    user: "James Okafor",
    userId: "u3",
    role: "director",
    text: "The plumber confirmed the isolation valve can remain closed between uses until the replacement arrives.",
    timestamp: "2025-08-08T16:05:00",
    isUnread: false,
  },
  {
    id: "cmt1",
    recordId: "rec1",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    text: "Rachel, can you upload the signed director attestation page so we can submit the full renewal package? DCF deadline is August 15th.",
    timestamp: "2025-07-30T14:25:00",
    isUnread: false,
  },
  {
    id: "cmt2",
    recordId: "rec1",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    text: "Understood. I have the signed page in hand — uploading the corrected version now.",
    timestamp: "2025-07-30T16:10:00",
    isUnread: true,
  },
  {
    id: "cmt3",
    recordId: "rec5",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    text: "James, please confirm the follow-up meeting date and share the parent's written response once received.",
    timestamp: "2025-07-27T09:07:00",
    isUnread: false,
  },
  {
    id: "cmt4",
    recordId: "rec5",
    user: "James Okafor",
    userId: "u3",
    role: "director",
    text: "Follow-up meeting is scheduled for August 5th at 2:00 PM. I will upload the parent's written response by end of week.",
    timestamp: "2025-07-28T08:30:00",
    isUnread: false,
  },
  {
    id: "cmt5",
    recordId: "rec6",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    text: "Priya, please verify that the DCF incident report was submitted within the 1-hour window and attach the confirmation number.",
    timestamp: "2025-07-29T16:00:00",
    isUnread: true,
  },
  {
    id: "cmt6",
    recordId: "rec9",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    text: "Rachel, keep HR in the loop. I want a status update by Friday.",
    timestamp: "2025-08-01T09:00:00",
    isUnread: true,
  },
]

export const NOTIFICATIONS: Notification[] = [
  {
    id: "mnotif1",
    type: "maintenance",
    title: "Maintenance approval required",
    message: "Preschool Classroom AC Not Cooling is awaiting Owner approval.",
    timestamp: "2025-08-08T10:15:00",
    recordId: "maint2",
    source: "maintenance",
    isRead: false,
  },
  {
    id: "mnotif2",
    type: "maintenance",
    title: "Repair completed",
    message: "North Toilet — Toddler Restroom was marked completed and an invoice was uploaded.",
    timestamp: "2025-08-06T15:40:00",
    recordId: "maint1",
    source: "maintenance",
    isRead: true,
  },
  {
    id: "notif1",
    type: "upload",
    title: "New record uploaded",
    message: "Priya Nair uploaded a Child Enrollment File at Sanford Learning Center.",
    timestamp: "2025-08-04T10:20:00",
    recordId: "rec10",
    isRead: false,
  },
  {
    id: "notif2",
    type: "upload",
    title: "New record uploaded",
    message: "Rachel Torres uploaded a Staff Complaint record at Lake Mary Learning Center.",
    timestamp: "2025-08-01T08:45:00",
    recordId: "rec9",
    isRead: false,
  },
  {
    id: "notif3",
    type: "attention",
    title: "Record needs attention",
    message: "CCIR – Allergic Reaction Incident at Sanford requires your review.",
    timestamp: "2025-07-29T13:58:00",
    recordId: "rec6",
    isRead: false,
  },
  {
    id: "notif4",
    type: "comment",
    title: "Director replied",
    message: "Rachel Torres replied to Annual DCF Licensing Renewal discussion.",
    timestamp: "2025-07-30T16:10:00",
    recordId: "rec1",
    isRead: true,
  },
  {
    id: "notif5",
    type: "upload",
    title: "Licensing inspection report uploaded",
    message: "Priya Nair uploaded the State Licensing Inspection report at Sanford.",
    timestamp: "2025-07-31T16:30:00",
    recordId: "rec8",
    isRead: true,
  },
]
